# Configuration file for Spaceship Titanic Deep Learning Solution
# All hyperparameters and settings are defined here for easy experimentation

# Data Configuration
data:
  train_path: "train.csv"
  test_path: "test.csv"
  validation_split: 0.2
  random_seed: 42

# Enhanced Model Architecture
model:
  hidden_sizes: [512, 256, 128, 64]
  dropout_rates: [0.2, 0.3, 0.4, 0.5]
  activation: "swish"  # Options: relu, leaky_relu, elu, gelu, swish, tanh, sigmoid
  use_batch_norm: true
  use_layer_norm: false
  use_residual: true
  output_size: 1

# Enhanced Training Configuration
training:
  batch_size: 32  # Smaller batch size for better generalization
  epochs: 150
  learning_rate: 0.0005  # Lower learning rate for better convergence
  weight_decay: 0.0005  # Increased regularization
  optimizer: "adamw"  # Options: adam, adamw, sgd, rmsprop
  
  # Enhanced Loss Function
  loss:
    type: "label_smoothing"  # Options: bce, label_smoothing, focal
    smoothing: 0.1  # For label smoothing
    alpha: 1.0      # For focal loss
    gamma: 2.0      # For focal loss
  
  # Gradient Clipping
  gradient_clipping:
    enabled: true
    max_norm: 1.0
  
  # Enhanced Learning Rate Scheduler
  scheduler:
    type: "cosine"  # Options: step, cosine, exponential, plateau
    step_size: 30
    gamma: 0.7
    patience: 8  # For plateau scheduler
    factor: 0.6   # For plateau scheduler
  
  # Enhanced Early Stopping
  early_stopping:
    patience: 20
    min_delta: 0.00005
    restore_best_weights: true

# ClearML Configuration
clearml:
  project_name: "Spaceship_Titanic"
  task_name: "Neural_Network_Classifier"
  tags: ["deep_learning", "classification", "kaggle"]
  auto_connect_frameworks: true
  auto_connect_arg_parser: true
  
  # Account Configuration
  # Replace with your actual ClearML credentials
  # Get these from: https://app.clear.ml/settings/workspace-configuration
  api:
    web_server: "https://app.clear.ml"
    api_server: "https://api.clear.ml"
    files_server: "https://files.clear.ml"
    # Uncomment and add your credentials:
    # access_key: "YOUR_ACCESS_KEY_HERE"
    # secret_key: "YOUR_SECRET_KEY_HERE"

# Evaluation Metrics
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1", "auc"]
  print_confusion_matrix: true

# Output Configuration
output:
  model_save_path: "best_model.pth"
  submission_file: "submission.csv"
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR
  save_predictions: true
  
# Hardware Configuration
hardware:
  device: "auto"  # Options: auto, cpu, cuda, mps
  num_workers: 4  # For data loading
  pin_memory: true

# Reproducibility
reproducibility:
  seed: 42
  deterministic: true
  benchmark: false